# Generated by Django 5.2.15 on 2026-06-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pdesc', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('pcategory', models.CharField(max_length=100)),
                ('trading', models.BooleanField(default=False)),
                ('offer', models.BooleanField(default=False)),
                ('pimage', models.ImageField(default='defaultimg.jpg', upload_to='uploads/')),
            ],
        ),
    ]
