# Generated by Django 5.2.15 on 2026-06-08 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='paname',
            new_name='pname',
        ),
    ]
